/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 *
 * @file AIOpenApiProxyImpl.h
 * This header file contains the declaration of the skeleton for all interfaces.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _AIOpenApiPROXY_IMPL_H_
#define _AIOpenApiPROXY_IMPL_H_

#include "AIOpenApi.h"
#include <rpcdds/utils/Messages.h>

namespace AI {

namespace OpenApi {
/*!
 * @brief This class is the skeleton of the servant and its remote procedures has to be implemented.
 * @ingroup AIOPENAPI
 */
class VSPProxyImpl : public VSPNotifyHandle {
public:
    //! @brief The default constructor.
    VSPProxyImpl() {}

    //! @brief Destructor.
    virtual ~VSPProxyImpl(){}

    ;
};

/*!
 * @brief This class is the skeleton of the servant and its remote procedures has to be implemented.
 * @ingroup AIOPENAPI
 */
class PhotoProxyImpl : public PhotoNotifyHandle {
public:
    //! @brief The default constructor.
    PhotoProxyImpl() {}

    //! @brief Destructor.
    virtual ~PhotoProxyImpl(){}

    ;
};

};  // namespace OpenApi

};  // namespace AI

#endif  // _AIOpenApiPROXY_IMPL_H_