/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 *
 * @file AIOpenApiServerImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "AIOpenApiServerImplExample.h"

bool VSPServerImplExample::beginVoiceHandle(const std::string& sendId) {
    bool return_ = false;

    return return_;
}
bool VSPServerImplExample::stopVoiceHandle(const std::string& sendId) {
    bool return_ = false;

    return return_;
}

std::string PhotoServerImplExample::getPhotoInfoHandle(const std::string& sendId, /*in*/ const std::string& pId) {
    std::string return_;

    return return_;
}
