/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 *
 * @file UCarProxyImpl.h
 * This header file contains the declaration of the skeleton for all interfaces.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _UCarPROXY_IMPL_H_
#define _UCarPROXY_IMPL_H_

#include "UCar.h"
#include <rpcdds/utils/Messages.h>

/*!
 * @brief This class is the skeleton of the servant and its remote procedures has to be implemented.
 * @ingroup UCAR
 */
class UCarProxyImpl : public UCarNotifyHandle {
public:
    //! @brief The default constructor.
    UCarProxyImpl() {}

    //! @brief Destructor.
    virtual ~UCarProxyImpl(){}

    ;
};

#endif  // _UCarPROXY_IMPL_H_