/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file CalculatorAsyncSupport.h
 * This header file contains functionality to use asynchronous calls for all interfaces.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _Calculator_DDS_ASYNC_SUPPORT_H_
#define _Calculator_DDS_ASYNC_SUPPORT_H_

#include <rpcdds/transports/dds/RTPSAsyncTask.h>
#include <rpcdds/exceptions/UserException.h>
#include "CalculatorAsyncCallbackHandlers.h"
#include "CalculatorTopics.h"




/*!
 * @brief This class represents a asynchronous task created to wait the reply of the procedure Calculator::sendTouchEvent from the server in an asynchronous call.
 * @ingroup CALCULATOR
 */
class Calculator_sendTouchEventTask : public eprosima::rpc::transport::dds::RTPSAsyncTask
{
    public:

        /*!
         * @brief The default constructor.
         *
         * @param obj Object that implements the callbacks that FastRPC will call when
         *            the reply will be received or and exception will be launched.
         * @param client Pointer to the server's proxy. Cannot be NULL.
         */
        Calculator_sendTouchEventTask(Calculator_sendTouchEventCallbackHandler &obj);

        //! @brief Destructor.
        virtual ~Calculator_sendTouchEventTask();
        
        /*!
         * @brief This funcion is called when the reply sample is received.
         */
        virtual void execute();
        
        /*!
         * @brief This function is called when an exception occurs.
         *        This exception can be launched in the server's side or in the client's side.
         *
         * @param ex The exception that will be launched.
         */
        virtual void on_exception(const eprosima::rpc::exception::SystemException &ex);        

        
        /*!
         * @brief This function returns the object used by the task.
         *
         * @return The object that implements the callbacks.
         */
        Calculator_sendTouchEventCallbackHandler& getObject();

        /*!
         * @brief This function returns the allocated reply sample.
         * @return Pointer to the allocated reply sample.
         */
        virtual void* getReplyInstance();
        
        private:
        
        Calculator_sendTouchEventCallbackHandler &m_obj;

        Calculator_Reply m_reply;
};

/*!
 * @brief This class represents a asynchronous task created to wait the reply of the procedure Calculator::sendGotoForeground from the server in an asynchronous call.
 * @ingroup CALCULATOR
 */
class Calculator_sendGotoForegroundTask : public eprosima::rpc::transport::dds::RTPSAsyncTask
{
    public:

        /*!
         * @brief The default constructor.
         *
         * @param obj Object that implements the callbacks that FastRPC will call when
         *            the reply will be received or and exception will be launched.
         * @param client Pointer to the server's proxy. Cannot be NULL.
         */
        Calculator_sendGotoForegroundTask(Calculator_sendGotoForegroundCallbackHandler &obj);

        //! @brief Destructor.
        virtual ~Calculator_sendGotoForegroundTask();
        
        /*!
         * @brief This funcion is called when the reply sample is received.
         */
        virtual void execute();
        
        /*!
         * @brief This function is called when an exception occurs.
         *        This exception can be launched in the server's side or in the client's side.
         *
         * @param ex The exception that will be launched.
         */
        virtual void on_exception(const eprosima::rpc::exception::SystemException &ex);        

        
        /*!
         * @brief This function returns the object used by the task.
         *
         * @return The object that implements the callbacks.
         */
        Calculator_sendGotoForegroundCallbackHandler& getObject();

        /*!
         * @brief This function returns the allocated reply sample.
         * @return Pointer to the allocated reply sample.
         */
        virtual void* getReplyInstance();
        
        private:
        
        Calculator_sendGotoForegroundCallbackHandler &m_obj;

        Calculator_Reply m_reply;
};









#endif // _Calculator_DDS_ASYNC_SUPPORT_H_