/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 *
 * @file CalculatorProxyImplExample.h
 * This header file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _CalculatorPROXY_IMPL_EXAMPLE_H_
#define _CalculatorPROXY_IMPL_EXAMPLE_H_

#include "CalculatorProxyImpl.h"
#include <cstdint>

/*!
 * @brief This class is an example of a servant and it implements the remote procedures of the servant.
 * @ingroup CALCULATOR
 */
class CalculatorProxyImplExample : public CalculatorProxyImpl {
public:
    //! @brief The default constructor.
    CalculatorProxyImplExample() {}

    //! @brief Destructor.
    virtual ~CalculatorProxyImplExample() {}
    void videoInitialized(VideoType type, const VideoFormat& videFormat) override;
    void videoDataReceived(VideoType type, int32_t size, const ByteArray& byte) override;
};

#endif  // _CalculatorPROXY_IMPL_EXAMPLE_H_
