/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file ucarProxyImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "ucarProxyImplExample.h"




















void UCarProxyImplExample::videoInitializedHandle(/*in*/ int32_t type, /*in*/ const VideoFormat& videFormat)
{
   
}
void UCarProxyImplExample::videoDataReceivedHandle(/*in*/ int32_t type, /*in*/ int32_t size, /*in*/ const ByteArray& byte)
{
   
}
void UCarProxyImplExample::requestGotoHUDesktopHandle()
{
   
}
void UCarProxyImplExample::audioStateChangedHandle(/*in*/ int32_t var2, /*in*/ const AudioFormat& audioFormat, /*in*/ int32_t playerState)
{
   
}
void UCarProxyImplExample::audioDataReceivedHandle(/*in*/ int32_t var2, /*in*/ int32_t var3, /*in*/ const ByteArray& var4)
{
   
}
void UCarProxyImplExample::musicInfoReceivedHandle(/*in*/ const MusicInfo& var2)
{
   
}
void UCarProxyImplExample::navigationInfoReceivedHandle(/*in*/ const NavigationInfo& var2)
{
   
}
void UCarProxyImplExample::phoneStateInfoReceivedHandle(/*in*/ const PhoneStateInfo& var2)
{
   
}
void UCarProxyImplExample::micRecordRequestHandle(/*in*/ const AudioFormat& var2, /*in*/ bool var3)
{
   
}
void UCarProxyImplExample::userInterventionNeededHandle()
{
   
}





















