/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file ucarServerImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "ucarServerImplExample.h"









bool UCarServerImplExample::sendTouchEventHandle(/*in*/ int32_t action, /*in*/ int32_t width, /*in*/ int32_t height, /*in*/ int32_t count, /*in*/ const LongArray& trackID, /*in*/ const LongArray& x, /*in*/ const LongArray& y)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::sendMicRecordDataHandle(/*in*/ int32_t i, /*in*/ const ShortArray& shorts, /*in*/ int32_t l)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::sendKeyEventHandle(/*in*/ int32_t keyEventActionType, /*in*/ int32_t keyCodeType, /*in*/ int32_t i)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::sendGotoForegroundHandle()
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::sendGotoBackgroundHandle()
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::sendVRCMDHandle(/*in*/ int32_t vrcmdType, /*in*/ const std::string& s)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::notifyIsCallHungUpHandle()
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::notifySwitchDayOrNightHandle(/*in*/ int32_t dayNightMode)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::awakenVoiceAssistantHandle(/*in*/ const ByteArray& bytes, /*in*/ const AudioFormat& audioFormat)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::presetVendorCustomFieldsHandle(/*in*/ const ByteArray& bytes)
{
    bool  return_ = false;
   
    return return_;
}
bool UCarServerImplExample::presetConnectModeHandle(/*in*/ int32_t connectMode)
{
    bool  return_ = false;
   
    return return_;
}































