/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 *
 * @file CalculatorProxyImplExample.cxx
 * This source file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "CalculatorProxyImplExample.h"

void CalculatorProxyImplExample::status_notify(/*in*/ int32_t value1, /*in*/ int32_t value2) {
    printf("status_notify:value1:%d  value2:%d\n", value1, value2);
}
