/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * rpcdds_LICENSE file included in this rpcdds distribution.
 *
 *************************************************************************
 * 
 * @file CalculatorProxyImplExample.h
 * This header file contains an example of the declaration of a servant.
 *
 * This file was generated by the tool rpcddsgen.
 */

#ifndef _CalculatorPROXY_IMPL_EXAMPLE_H_
#define _CalculatorPROXY_IMPL_EXAMPLE_H_

#include "CalculatorProxyImpl.h"

/*!
 * @brief This class is an example of a servant and it implements the remote procedures of the servant.
 * @ingroup CALCULATOR
 */
class CalculatorProxyImplExample : public CalculatorProxyImpl
{
    public:

        //! @brief The default constructor.
        CalculatorProxyImplExample(){}

        //! @brief Destructor.
        virtual ~CalculatorProxyImplExample(){}
 

        void status_notify(/*in*/ int32_t value1,/*in*/ int32_t value2);
};


#endif // _CalculatorPROXY_IMPL_EXAMPLE_H_
